version: '3'
services:
  web:
    container_name: "portal"
    build: .
    ports:
      - "9191:9191"
    # - "7537:7537"
    expose:
      - "7537"
    volumes:
      - './logs/portal/app.log:./app.log'

  nginx:
    container_name: "nginx"
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./index.html:/usr/share/nginx/html/index.html:ro"
      - './logs/nginx:/var/log/nginx'
