version: '3'
services:
  web:
    container_name: "portal"
    build: .
    ports:
      - "9191:9191"
    # - "7537:7537"
    expose:
      - "7537"
    networks:
      uwsgi:
        aliases:
          - portal

  nginx:
    container_name: "nginx"
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./index.html:/usr/share/nginx/html/index.html:ro"
      - './nginx/log:/var/log/nginx'
    networks:
      - uwsgi
networks:
  uwsgi